service: ssr-react-next-christian

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  memorySize: 512
  environment:
    NODE_ENV: production

functions:
  server:
    handler: index.server
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary
  - serverless-domain-manager

custom:
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: nextjs.eu-west-1.demoapp.dev.app.york.ac.uk
    basePath: ''
    stage: dev
    createRoute53Record: false
    autoDomain: true
    endpointType: regional
