on: push
jobs:
  deploy_to_aws:
    runs-on: ubuntu-latest
    steps:

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Check out the application's source code
        uses: actions/checkout@v2

      - name: Install application dependencies
        run: npm ci

      - name: Deploy application using Serverless
        run: npm run deploy
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-1